<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_jumlahRp 18,000Order IDsample-store-160_d46abb</name>
   <tag></tag>
   <elementGuidId>27b4cef2-cd6c-47ff-8a2e-ca0c78429357</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='application']/div[4]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.main-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-container</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>jumlahRp 18,000Order IDsample-store-1605525230Nomor kartu•••• •••• •••• 1114×Hapus KartuBerlaku hinggaCVVPembayaran aman dengan MidtransPilih PromoPotongan 10 Rupiah- Rp 10Potongan 10% - Demo Promo Engine- Rp 2,000EmailNo telp.Kartu Kredit/DebitBayar dengan Kartu Visa, MasterCard, JCB, atau Amex1 informasi kartu tersimpanpromoBCA KlikPayBayar dengan BCA KlikPayKlikBCABayar dengan akun KlikBCA Andae-Pay BRIBayar dengan akun e-Pay BRI AndaOCTO ClicksBayar dengan akun OCTO Clicks AndaDanamon Online BankingBayar dengan akun Danamon Online Banking AndaATM/Bank TransferBayar dari ATM Bersama, Prima, atau AltoIndomaretBayar di IndomaretTelkomsel CashBayar dengan akun Telkomsel Cash AndaLINE Pay e-cash | mandiri e-cashBayar dengan akun LINE Pay e-cash | mandiri e-cash AndaGoPay/e-Wallet LainnyaScan kode QR dengan GoPay atau e-wallet lainnyaAkulakuBayar dengan akun Akulaku AndaAlfa GroupBayar di gerai Alfamart, Alfamidi, atau Dan+Dan.ShopeePay/e-Wallet LainnyaScan kode QR dengan ShopeePay atau e-wallet lainnya</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;main-container&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application']/div[4]/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bayar Sekarang'])[1]/following::div[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='id'])[1]/following::div[8]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div</value>
   </webElementXpaths>
</WebElementEntity>
